POST = 'POST'
GET = 'GET'
PUT = 'PUT'
DELETE = 'DELETE'
HEAD = 'HEAD'
CONNECT = 'CONNECT'
OPTIONS = 'OPTIONS'
TRACE = 'TRACE'
PATCH = 'PATCH'


def get_methods_list():
    return [GET, HEAD, POST, PUT, DELETE, CONNECT, OPTIONS, TRACE, PATCH]
